name: PR action

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print some info
      run: |
        echo event: ${{ JSON.stringify(github.event) }}
        echo GITHUB_SHA: $GITHUB_SHA,
        echo GITHUB_REF: $GITHUB_REF,
        echo
        echo file1:
        cat file1.txt
        echo
        echo file2:
        cat file2.txt
