name: PR action

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print some info
      run: |
        echo GITHUB_SHA: $GITHUB_SHA,
        echo GITHUB_REF: $GITHUB_REF,
        echo
        ls -laFh

