name: PR action

on: [pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nonce-file
    - name: Print some info
      run: |
        echo "reading nonce.txt"
        cat nonce.txt
        echo GITHUB_SHA: $GITHUB_SHA,
        echo GITHUB_REF: $GITHUB_REF,
        echo
        echo file1:
        cat file1.txt
        echo
        echo file2:
        cat file2.txt
        echo
        echo "writing nonce.txt"
        echo "GITHUB_SHA: $GITHUB_SHA" >nonce.txt
        echo "GITHUB_REF: $GITHUB_REF" >>nonce.txt
    - name: Upload artifact
      uses: actions/upload_artifact@v2
      with:
        name: nonce-file
