name: PR action

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print some info
      run: |
        echo GITHUB_SHA: $GITHUB_SHA,
        echo GITHUB_REF: $GITHUB_REF,
        echo
        ls -laFh
    - name: step 1
      run: echo "step 1"; false
    - name: step 2
      run: echo "step 2"; false
    - name: step 3
      run: echo "step 3"; false
    - name: step 4
      run: echo "step 4"; false

